[tox]
envlist =
    py3.{12,11,10,9,8}
    minimal
    style
    typing
    docs
skip_missing_interpreters = true

[testenv]
package = wheel
wheel_build_env = .pkg
constrain_package_deps = true
use_frozen_constraints = true
dependency_groups = tests
commands = pytest -v --tb=short --basetemp={envtmpdir} {posargs}

[testenv:minimal]
deps =
commands = python -c "from flask_debugtoolbar import DebugToolbarExtension"

[testenv:style]
dependency_groups = pre-commit
skip_install = true
commands = pre-commit run --all-files

[testenv:typing]
dependency_groups = typing
commands =
    mypy
    pyright
    pyright --verifytypes flask_debugtoolbar --ignoreexternal

[testenv:docs]
dependency_groups = docs
commands = sphinx-build -E -W -b dirhtml docs docs/_build/dirhtml

[testenv:update-pre_commit]
labels = update
dependency_groups = pre-commit
skip_install = true
commands = pre-commit autoupdate -j4

[testenv:update-requirements]
base_python = 3.8
labels = update
skip_install = true
commands =
    uv lock -U {posargs}
